services:
  discord-qbittorrent-bot:
    build: .
    container_name: discord-qbt-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=YOUR_DISCORD_BOT_TOKEN
      - QBITTORRENT_URL=YOUR_QBITTORRENT_URL
      - QBITTORRENT_USERNAME=YOUR_USERNAME
      - QBITTORRENT_PASSWORD=YOUR_PASSWORD
      - LOG_LEVEL=INFO
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

